# Change these first
owner: upptime # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: UP-TO-DATE WebDesign (BE)
    url: https://www.uptodatewebdesign.be
  - name: UP-TO-DATE WebDesign
    url: https://www.uptodatewebdesign.com
  - name: UP-TO-DATE Today
    url: https://www.uptodate-today.be/
  - name: UP-TO-DATE Events
    url: https://events.uptodatewebdesign.be/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptodate-sites
  logoUrl: https://www.uptodatewebdesign.be/wp-content/uploads/avatar-utd.png
  name: UP-TO-DATE Sites Status
  introTitle: "UTD Sites Status Checker"
  introMessage: List of websites UP-TO-DATE WebDesign manage and maintain [**Visit Us**](https://www.uptodatewebdesign.com)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration