# Change these first
owner: jgui1129 # Your GitHub username
repo: uptodate-sites # Your Github repository name

# Add your sites here
sites:
  - name: UP-TO-DATE WebDesign (BE)
    url: https://www.uptodatewebdesign.be
  - name: UP-TO-DATE WebDesign
    url: https://www.uptodatewebdesign.com
  - name: UP-TO-DATE Today
    url: https://www.uptodate-today.be
  - name: UP-TO-DATE Events
    url: https://events.uptodatewebdesign.be
  - name: Smart-Site
    url: https://www.smart-site.be
  - name: Smart-Site Vastgoed
    url: https://vastgoed-smart-site.blogspot.com
  - name: Smart-Site Bouw
    url: https://bouw-smart-site.blogspot.com
  - name: Dipsss
    url: https://www.dipsss.be
  - name: Smart-Site Zone
    url: https://www.kinderrijck.be
  - name: Kinderrijck
    url: https://www.kinderrijck.be
  - name: De Volmolen
    url: https://www.vakantieverblijfvolmolen.be
  - name: Boetiek Shanna
    url: https://www.boetiekshanna.be
  - name: Bexx Verhuur
    url: https://www.bexxverhuur.be
  - name: TCMS
    url: https://www.tcms.be
  - name: Clima Concept
    url: https://www.climaconcept.be/
  - name: ABC Villa
    url: https://www.abcvilla.be

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptodate-sites
  logoUrl: https://www.uptodatewebdesign.be/wp-content/uploads/avatar-utd.png
  name: UP-TO-DATE Sites Status
  introTitle: "UTD Sites Status Checker"
  introMessage: List of websites UP-TO-DATE WebDesign manage and maintain [**Visit Us**](https://www.uptodatewebdesign.com)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration